name: Publish
description: Publish to npm

inputs:
  token:
    description: 'npm token'
    required: true

runs:
  steps:
    # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm
    # see https://docs.npmjs.com/generating-provenance-statements
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ./.github/actions/prepare
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: npm publish --provenance --access public --registry https://registry.npmjs.org
      shell: bash
  using: composite
