name: Publish
description: Publish to npm

inputs:
  token:
    description: 'npm token'
    required: true

runs:
  steps:
    # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm
    # see https://docs.npmjs.com/generating-provenance-statements
    - name: Checkout Repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - uses: ./.github/actions/prepare
    - name: Publish to npm
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
      run: npm publish --provenance --access public --registry https://registry.npmjs.org
      shell: bash
  using: composite
