description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '22'
    - name: Install dependencies
      uses: bahmutov/npm-install@6bbff949458c1dd99b20e185cee8c4d6fcf1212a # v1.10.9
      with:
        install-command: npm ci --foreground-scripts
  using: composite
