jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - uses: ./.github/actions/prepare
      - run: npm run lint:md

name: Lint Markdown

on:
  pull_request: ~
  push:
    branches:
      - main
