name: release-please

concurrency:
  group: ${{ github.workflow }}

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: release
        uses: googleapis/release-please-action@26ac09bebf9d65ff1137edead58f239dd5a04faa # v4

      # see https://github.com/google-github-actions/release-please-action#automating-publication-to-npm
      - name: Checkout Repository
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        if: ${{ steps.release.outputs.release_created }}
        uses: bahmutov/npm-install@7639f1c46981fc8c8d64ec6be729b7ddbd7ddc52 # v1.10.7

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --provenance --access public
