concurrency:
  group: ${{ github.workflow }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          ref: main
      - uses: ./.github/actions/prepare
      - run: npm run build
      - env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        uses: JoshuaKGoldberg/release-it-action@a5e9120c1c7bb2d6a4e9f86b9464cf830e215ae7 # v0.2.3

name: Release

on: workflow_dispatch

permissions:
  contents: write
  id-token: write
